models/OrderType.php
<?php

namespace  app\models;
use Yii;
use yii\db\ActiveRecord;

class OrderType extends ActiveRecord
{
    public static function getDb()
    {
        return Yii::$app->db;
    }

    public static function tableName()
    {
        return 'order_type';
    }

    public function getId()
    {
        return $this->id;
    }
}

models/Orders.php
<?php

namespace  app\models;
use Yii;
use yii\db\ActiveRecord;

class Orders extends ActiveRecord
{
    public static function getDb()
    {
        return Yii::$app->db;
    }

    public static function tableName()
    {
        return 'orders';
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTables(){
        return $this->hasOne(Tables::className(), ['id' => 'table_id']);
    }

    public function getMovements(){
        return $this->hasOne(Movements::className(), ['id' => 'movement_id']);
    }

    public function getOrderType(){
        return $this->hasOne(OrderType::className(), ['id' => 'order_type_id']);
    }

    public function getOrderPlates(){
        return $this->hasMany(OrderPlates::className(), ['order_id' => 'id']);
    }

    public function getPlates(){
        return $this->getOrderPlates()->joinWith('plates');
    }

    public function getFoods(){
        return $this->getOrderPlates()->joinWith('foods');
    }
}

models/OrdersForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

class OrdersForm extends Model
{
    public $id;
    public $order;
    public $observations;
    public $table_id;
    public $order_type_id;
    public $additional;
    public $cost;
    public $coupon;
    public $offer_id;
    public $created_at;
    public $updated_at;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [[
                'table_id',
                'order_type_id',
            ], 'required', 'message' => 'Este campo es requerido.'],

            [[
                'order',
                'observations',
                'table_id',
                'order_type_id',
            ], 'string', 'max' => 255, 'tooLong' => 'Supero el numero maximo de caracteres.'],

            [[
                'cost',
                'additional',
            ], 'double', 'max' => 1000000, 'tooBig' => 'El sistema no soporta numeros tan grandes de {attribute}.', 'message' => 'Numero debe ser valido'],
        ];
    }
}

controllers/OrdersController.php
<?php

namespace app\controllers;

use app\components\Calculate;
use app\models\Movements;
use app\models\Offers;
use app\models\OrderPlates;
use app\models\OrderPlatesForm;
use app\models\OrderType;
use app\models\Plates;
use DateTime;
use app\models\Tables;
use Yii;
use yii\web\Controller;
use app\models\Orders;
use app\models\OrdersForm;
use yii\helpers\Html;
use yii\helpers\Url;


class OrdersController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function beforeAction($action)
    {
        if ($action->id == 'data' || $action->id == 'calculate-totals') {
            $this->enableCsrfValidation = false;
        }

        if (parent::beforeAction($action)){
            if (Yii::$app->user->isGuest){
                return $this->redirect(['usuario/login']);
            }
        }

        return parent::beforeAction($action);
    }

    public function actionList()
    {
        return $this->render('list');
    }

    public function actionData(){
        $data = Yii::$app->request->post();
        $pos = ['tables.name', 'orders.created_at', 'movements.cost', 'orders.observations', 'orders.completed', 'orders.id'];

        $searchName = $data['columns'][0]['search']['value'];
        $searchDir = $data['columns'][1]['search']['value'];
        // TODO: Añadir mas opciones de busqueda
        $conditions = ($searchName) ? "description LIKE '%$searchDir%'":'';

        $order = $pos[$data['order'][0]['column']];
        $orderDir = $data['order'][0]['dir'] == 'asc' ? SORT_ASC : SORT_DESC;

        $query = Orders::find()
            ->joinWith(['tables', 'movements', 'orderType'])
            ->where($conditions);
        if (Yii::$app->user->identity->id !== 1)
        {
            $query = $query->andWhere(['orders.establishment_id' => Yii::$app->user->identity->establishment_id]);
        }

        if ($data['StatusFilter'] || $data['StatusFilter'] === '0')
        {
            $query = $query->andWhere(['orders.completed' => $data['StatusFilter']]);
        }

        if ($data['DateMinFilter']) {
            $data['DateMinFilter'] = DateTime::createFromFormat('d / m / Y', $data['DateMinFilter'])->format('Y-m-d');
            $query->andWhere("DATE_FORMAT(orders.created_at, '%Y-%m-%d') >= DATE_FORMAT('{$data['DateMinFilter']}', '%Y-%m-%d')");
        }

        if ($data['DateMaxFilter']) {
            $data['DateMaxFilter'] = DateTime::createFromFormat('d / m / Y', $data['DateMaxFilter'])->format('Y-m-d');
            $query->andWhere("DATE_FORMAT(orders.created_at, '%Y-%m-%d') <= DATE_FORMAT('{$data['DateMaxFilter']}', '%Y-%m-%d')");
        }



        $result = $query->orderBy([$order => $orderDir])
            ->limit($data['length'])
            ->offset($data['start'])
            ->all();
        $total = Orders::find()->count();

        $response = [
            "draw"=> $data['draw'],
            "recordsTotal" => $total,
            "recordsFiltered" => $total,
            "data" => []
        ];

        foreach ($result as $row)
        {
            $buttons = '';
            if ($row->completed == 0) {
                $completed = 'En preparacion';
                $buttons .= Html::button('<i class="fa fa-check"></i>', ['class'=>"btn btn-sm btn-info", 'onclick' => "processButton({$row->id})", 'data-toggle'=>"tooltip", 'data-id' => $row->id, 'title'=>"Procesar"]);
                $buttons .= Html::a(Html::button('<i class="fa fa-cog"></i>', ['class'=>"btn btn-sm btn-primary", 'data-toggle'=>"tooltip", 'title'=>"Modificar"]), ['/orders/modify', 'id' => $row->id]);
                if (Yii::$app->user->identity->id === 1) {
                    $buttons .= Html::a(Html::button('<i class="fa fa-trash"></i>', ['class' => "btn btn-sm btn-danger", 'data-toggle' => "tooltip", 'title' => "Eliminar"]), ['/orders/delete', 'id' => $row->id]);
                }else{
                    $buttons .= Html::a(Html::button('<i class="fa fa-trash"></i>', ['class' => "btn btn-sm btn-danger", 'data-toggle' => "tooltip", 'title' => "Eliminar"]), ['/orders/process-order', 'id' => $row->id, 'completed' => 0]);
                }
            }
            else
            {
                $completed = $row->completed > 0 ? 'Entregado' : 'Cancelado';
            }


            $response['data'][] = [
                $row->tables->name,
                Yii::$app->formatter->format($row->created_at, 'datetime'),
                Yii::$app->formatter->format($row->movements->cost, 'currency'),
                $row->observations,
                $completed,
                $buttons
            ];
        }

        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return $response;
    }

    public function actionNew()
    {
        $orderModel = new OrdersForm();
        $platesModel = new OrderPlatesForm;

        if (Yii::$app->request->isPost)
        {

            $post_data = Yii::$app->request->post();
            $plates = $post_data['plates'];

            // Elimina los platos mal cargados o con formato corrupto
            $plates = $platesModel->customFilter($plates);
            $orderModel->load($post_data);

            // Valida si esta bien, sino explota.
            if (!$orderModel->validate())
            {
                throw new \Exception('Parametros no son validos: '.implode($orderModel, ', '));
            }

            if (empty($plates)) throw new \Exception("No se ingresaron los platos correctamente.");

            $transaction = Yii::$app->db->beginTransaction();

            try
            {
                $totals = Calculate::calculateOrder($plates, $orderModel);
                // Ingresa el movimiento en la base de datos
                $movement = new Movements();
                $movement->cost = $totals['total'];
                $movement->origin = 'order';
                $movement->user_id = Yii::$app->user->identity->id;
                $movement->insert();

                $movement_id = Yii::$app->db->getLastInsertID();

                // Crea la entidad principal de la orden
                $db_models = new Orders();
                $db_models->additional = $orderModel->additional;
                $db_models->movement_id = $movement_id;
                $db_models->order_type_id = $orderModel->order_type_id;
                $db_models->table_id = $orderModel->table_id;
                $db_models->coupon_id = $orderModel->coupon;
                $db_models->offer_id = $orderModel->offer_id;
                $db_models->observations = $orderModel->observations;
                $db_models->completed = 0;
                $db_models->establishment_id = Yii::$app->user->identity->establishment_id;
                $db_models->user_id = Yii::$app->user->identity->id;
                $db_models->created_at = date('Y-m-d H:i:s');
                $db_models->insert();

                $order_id = Yii::$app->db->getLastInsertID();

                foreach ($plates as $plate)
                {
                    $order_plate = new OrderPlates();
                    $order_plate->order_id      = $order_id;
                    $order_plate->plate_id      = $plate['plate_id'];
                    $order_plate->food_id       = $plate['food_id'];
                    $order_plate->amount        = $plate['amount'];
                    $order_plate->description   = $plate['description'];
                    $order_plate->extra_cost    = $plate['extra_cost'];
                    $order_plate->insert();
                }

                $transaction->commit();

                if (Yii::$app->request->isAjax)
                {
                    Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return ['success' => 1, 'redirect' => Url::to(['orders/list']), 'msg' => 'Orden creada con exito, redirigiendo al listado.'];
                }
                return $this->redirect(['/orders/list']);
            }
            catch (\Throwable $e)
            {
                $transaction->rollBack();
                throw new \Exception("Se encontro un error en el registro: ".$e->getMessage());
            }
        }

        $order_types = OrderType::find()->all();
        if (Yii::$app->user->identity->id !== 1) {
            $tables = Tables::find()->where(['establishment_id' => Yii::$app->user->identity->establishment_id])->all();
            $offers = Offers::find()->where(['establishment_id' => Yii::$app->user->identity->establishment_id])->all();
            $plateList = Plates::find()->where(['establishment_id' => Yii::$app->user->identity->establishment_id])->andWhere(['plates.deleted' => 0])->all();
        }else{
            $tables = Tables::find()->all();
            $offers = Offers::find()->all();
            $plateList = Plates::find()->where(['plates.deleted' => 0])->all();
        }

        $orderModel->order_type_id = 1;
        $platesModel->amount = 1;

        return $this->render('new', [
            'model' => $orderModel,
            'platesModel' => $platesModel,
            'order_types' => $order_types,
            'tables' => $tables,
            'offers' => $offers,
            'plateList' => $plateList,
        ]);
    }

    public function actionModify($id){
        $orderModel = new OrdersForm();
        $platesModel = new OrderPlatesForm;

        $order = Orders::find()->joinWith(['tables', 'plates', 'foods', 'movements', 'orderType'])->where(['orders.id' => $id])->one();
        if (empty($order))
        {
            throw new \Exception("Orden no encontrada.");
        }

        if (Yii::$app->request->isPost)
        {

            $post_data = Yii::$app->request->post();

views/orders/list.php
<?php
use  yii\helpers\Html;
use  yii\helpers\Url;
use brussens\bootstrap\select\Widget as Select;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;
?>


<div class="x_content">
    <div class="row">
        <h1>Menu 1</h1>
    </div>
    <div class="row">
        <div class="col-md-4 input-group">
            <input type="text" placeholder="Buscador" id="buscador" class="form-control">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
            </span>
        </div>
        <div class="col-md-2">
            <?= Html::a('<button class="btn btn-primary"><i class="fa fa-plus"></i> Crear nueva</button>', ['orders/new']) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <?= Html::label('Estado', 'StatusFilter') ?>
            <?= Select::widget([
                'name' => 'statusFilter',
                'value' => '0',
                'items' => ['1' => 'Completado', '0' => 'En preparacion', '-1' => 'Cancelado'],
                'options' => [
                    'id' => 'StatusFilter',
                    'class' => 'form-control',
                    'data-live-search' => 'true',
                    'prompt'=>'Todos'
                ]
            ]) ?>
        </div>
        <div class="col-md-3">
            <div class="col-md-6">
                <?= Html::label('Desde', 'DateMin') ?>
                <?= DatePicker::widget([
                    'language' => 'es',
                    'dateFormat' => 'dd / MM / yyyy',
                    'value' => date('d / m / Y'),
                    'options' => ['id' => 'DateMin', 'class' => 'form-control', 'autocomplete' => "off"]
                ]) ?>
            </div>
            <div class="col-md-6">
                <?= Html::label('Hasta', 'DateMax') ?>
                <?= DatePicker::widget([
                    'language' => 'es',
                    'dateFormat' => 'dd / MM / yyyy',
                    'value' => date('d / m / Y', strtotime("+1 day", strtotime(date('Y-m-d')))),
                    'options' => ['id' => 'DateMax', 'class' => 'form-control', 'autocomplete' => "off"]
                ]) ?>
            </div>
        </div>
    </div>

    <hr>
    <div class="table-responsive">
        <table id="datatable" class="table table-striped table-bordered">
            <thead>
            <tr>
                <th width="7%">Mesa</th>
                <th>Fecha pedido</th>
                <th>Costo</th>
                <th width="50%">Descripcion</th>
                <th>Estado</th>
                <th width="12%">accion</th>
            </tr>
            </thead>
        </table>
    </div>

</div>

<script>
    url = '<?=Url::to(['orders/data']);?>';
    processUrl = '<?=Url::to(['orders/process-order']);?>';
</script>
<?php
$this->registerJsFile(
    '@web/js/basic-table.js',
    ['depends' => [\yii\web\JqueryAsset::className(), 'fedemotta\datatables\DataTablesAsset',]]
);
?>

views/orders/modify.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\Json;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use brussens\bootstrap\select\Widget as Select;
?>

<h2>Modificar orden</h2>
<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data', 'id' => 'OrderForm']]) ?>

    <div class="row">
        <div class="form-group">
            <div class="col-md-3">
                <?=$form->field($model, 'order_type_id')->widget(Select::className(), [
                    'options' => ['data-live-search' => 'true', 'prompt'=>'Seleccione'],
                    'items' => ArrayHelper::map($order_types, 'id', 'name')
                ])->label('Tipo de pedido');?>
            </div>
            <div class="col-md-2">
                <?=$form->field($model, 'table_id')->widget(Select::className(), [
                    'options' => ['data-live-search' => 'true'],
                    'items' => ArrayHelper::map($tables, 'id', 'name')
                ])->label('Mesa del pedido');?>
            </div>
            <div class="col-md-2">
                <?=$form->field($model, 'offer_id')->widget(Select::className(), [
                    'options' => ['data-live-search' => 'true', 'prompt'=>'Seleccione', 'disabled' => true],
                    'items' => ArrayHelper::map($offers, 'id', 'name')
                ])->label('Oferta a aplicar');?>
            </div>
            <div class="col-md-2">
                <?= $form->field($model, 'coupon')->input('text', ['placeholder' => 'Ej: Px3H1314I', 'disabled' => true])->label('Cupon de descuento') ?>
            </div>
            <div class="col-md-2">
                <?= $form->field($model, 'additional')->input('number', ['placeholder' => 'Valor agregado', 'step' => 'any'])->label('Valor adicional') ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <div class="col-md-5">
                <?= $form->field($model, 'observations')->textarea(['placeholder' => 'Detalles del pedido'])->label('Detalles del pedido') ?>
            </div>
        </div>
    </div>
    <br>

    <div class="row">
        <div class="form-group">
            <div class="container-items"><!-- widgetContainer -->
                <div class="panel panel-default"><!-- widgetBody -->
                    <div class="panel-heading">
                        <h3 class="panel-title pull-left col-sm-1">Platos</h3>
                        <div class="pull-left col-sm-1">
                            <?= Html::button('<i class="glyphicon glyphicon-plus"></i>Agregar plato', ['id' => 'addPlate', 'class' => 'btn btn-success']) ?>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body item-container">
                        <?=$this->render('platesElement.php', ['plateList' => $plateList])?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class'=> 'btn btn-primary btn-lg']); ?>
    </div>
<?php ActiveForm::end() ?>


<?=$this->render('plateModal.php', ['model' => $platesModel, 'plateList' => $plateList, 'form' => $form])?>


<script>
    additionalsUrl = '<?=Url::to(['plates/get-plate'])?>';
    totalsUrl = '<?=Url::to(['orders/calculate-totals'])?>';
    plate_list = <?=Json::encode($orderPlates);?>;
</script>


<?php
$this->registerJsFile(
    '@web/js/orders.js',
    ['depends' => [\yii\web\JqueryAsset::className(), 'fedemotta\datatables\DataTablesAsset',]]
);
?>

views/orders/new.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use brussens\bootstrap\select\Widget as Select;

?>

<h2>Crear nueva orden</h2>
<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data', 'id' => 'OrderForm']]) ?>

<div class="row">
    <div class="form-group">
        <div class="col-md-3">
            <?=$form->field($model, 'order_type_id')->widget(Select::className(), [
                'options' => ['data-live-search' => 'true', 'prompt'=>'Seleccione'],
                'items' => ArrayHelper::map($order_types, 'id', 'name')
            ])->label('Tipo de pedido');?>
        </div>
        <div class="col-md-2">
            <?=$form->field($model, 'table_id')->widget(Select::className(), [
                'options' => ['data-live-search' => 'true'],
                'items' => ArrayHelper::map($tables, 'id', 'name')
            ])->label('Mesa del pedido');?>
        </div>
        <div class="col-md-2">
            <?=$form->field($model, 'offer_id')->widget(Select::className(), [
                'options' => ['data-live-search' => 'true', 'prompt'=>'Seleccione', 'disabled' => true],
                'items' => ArrayHelper::map($offers, 'id', 'name')
            ])->label('Oferta a aplicar');?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'coupon')->input('text', ['placeholder' => 'Ej: Px3H1314I', 'disabled' => true])->label('Cupon de descuento') ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'additional')->input('number', ['placeholder' => 'Valor agregado', 'step' => 'any'])->label('Valor adicional') ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="form-group">
        <div class="col-md-5">
            <?= $form->field($model, 'observations')->textarea(['placeholder' => 'Detalles del pedido'])->label('Detalles del pedido') ?>
        </div>
    </div>
</div>
    <br>
    <?=$this->render('platesElement.php', ['plateList' => $plateList])?>
    <hr>

<div class="form-group">
    <?= Html::submitButton('Guardar', ['class'=> 'btn btn-primary btn-lg']); ?>
</div>
<?php ActiveForm::end() ?>


<?=$this->render('plateModal.php', ['model' => $platesModel, 'plateList' => $plateList, 'form' => $form])?>


<script>
    additionalsUrl = '<?=Url::to(['plates/get-plate'])?>';
    totalsUrl = '<?=Url::to(['orders/calculate-totals'])?>';
    plate_list = [];
</script>

<?php
$this->registerJsFile(
    '@web/js/orders.js',
    ['depends' => [\yii\web\JqueryAsset::className(), 'fedemotta\datatables\DataTablesAsset',]]
);
?>

views/orders/plateModal.php
<?php
use yii\bootstrap\Modal;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use brussens\bootstrap\select\Widget as Select;
use yii\helpers\ArrayHelper;

Modal::begin([
    'header' => '<h4>Plato</h4>',
    'id'     => 'PlateModal',
    'size'   => 'model-lg',
]);
?>
    <div id='modelContent'>
        <?php $form = ActiveForm::begin(['options' => ['id' => 'PlateForm']]) ?>
        <div class="row">
            <div class="col-md-12">
            <?=$form->field($model, "plate_id")->widget(Select::className(), [
                'options' => [
                    'data-live-search' => 'true',
                    'prompt'=>'Seleccione',
                    'class' => 'form-control plate',
                    'id' => 'PlateSelect'
                ],
                'items' => ArrayHelper::map($plateList, 'id', 'name')
            ])->label('Plato');?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
            <?=$form->field($model, "food_id")->widget(Select::className(), [
                'options' => ['data-live-search' => 'true', 'prompt'=>'Ninguno', 'class' => 'form-control', 'id' => "FoodSelect"],
                'items' => []
            ])->label('Acompañamiento')?>
            </div>

        </div>
        <div class="row">
            <div class="col-sm-3">
                <?= $form->field($model, "amount")->input('number', ['maxlength' => true, 'placeholder' => 'Cantidad'])->label('Cantidad') ?>
            </div>
            <div class="col-md-2">
                <?=Html::label('Costo (U)'); ?>
                <?= Html::input('number', '', 0, ['type' => "number", 'class' => 'form-control', "id" => "PlateCost", "disabled" => "disabled"]); ?>
            </div>
            <div class="col-sm-4">
                <?= $form->field($model, "description")->textInput(['placeholder' => 'Especificaciones', 'maxlength' => true])->label('Especificaciones') ?>
            </div>
            <div class="col-sm-3">
                <?= $form->field($model, "extra_cost")->input('number', ['maxlength' => true, 'placeholder' => 'Valor agregado', 'step' => 'any'])->label('Costo ad. (U)') ?>
            </div>
        </div>


        <div class="row image-container">
            <?= Html::img('@web/img/default.png', ['class' => 'image-preview', 'id' => 'PlateImg']) ?>
        </div>

        <div class="row">
            <?= Html::submitButton('Guardar', ['class'=> 'btn btn-primary btn-xl']); ?>
        </div>
        <?php $form->end() ?>
    </div>
<?php Modal::end(); ?>

views/orders/platesElement.php
<?php
use yii\helpers\Html;
?>
<div class="row">
    <div class="form-group">
        <div class="container-items"><!-- widgetContainer -->
            <div class="panel panel-default"><!-- widgetBody -->
                <div class="panel-heading">
                    <h3 class="panel-title pull-left col-sm-1">Platos</h3>
                    <div class="pull-left col-sm-1">
                        <?= Html::button('<i class="glyphicon glyphicon-plus"></i>Agregar plato', ['id' => 'addPlate', 'class' => 'btn btn-success']) ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="panel-body item-container">
                    <div  style="overflow-x:auto;">
                        <table class="table table-striped table-responsive" id="PlateList">
                            <thead>
                            <tr>
                                <th>Plato</th>
                                <th>Acompañamiento</th>
                                <th>Cantidad</th>
                                <th>Especificacion</th>
                                <th>Costo adicional</th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td colspan="7">Vacia</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>

                    <div id="PlateListHidden"></div>
                </div>
                <div class="panel-footer">
                    <table class="table table-striped table-responsive">
                        <tr>
                            <td width="70%"></td>
                            <td>Descuento</td>
                            <td>$<span id="Discount">0</span></td>
                        </tr>
                        <tr>
                            <td width="70%"></td>
                            <td>Total</td>
                            <td>$<span id="Total">0</span></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>