models/Plates.php
<?php

namespace  app\models;
use Yii;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

class Plates extends ActiveRecord
{
    public static function getDb()
    {
        return Yii::$app->db;
    }

    public static function tableName()
    {
        return 'plates';
    }

    public function getId()
    {
        return $this->id;
    }

    public function getFoods()
    {
        return $this->hasMany(Foods::className(), ['plate_id' => 'id'])->andOnCondition(['foods.deleted' => false])->orderBy(['name' => SORT_DESC]);
    }

}

models/PlatesForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

class PlatesForm extends Model
{
    public $id;
    public $name;
    public $description;
    public $cost;
    public $img_url;
    public $created_at;
    public $updated_at;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [['name', 'description', 'cost',], 'required', 'message' => 'Este campo es requerido.'],
            [['name', 'description'], 'string', 'max' => 255, 'tooLong' => 'Supero el numero maximo de caracteres.'],
            [['cost'], 'double', 'max' => 1000000, 'tooBig' => 'El sistema no soporta numeros tan grandes de {attribute}.', 'message' => 'Numero debe ser valido'],
            [['img_url'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg'],
        ];
    }


    public function upload($old_pic=null, $id)
    {
        if ($this->validate()) {
            $image = false;
            if (!empty($this->img_url))
            {
                if ($old_pic)
                {
                    unlink(str_replace('@web/', '', $old_pic));
                }

                $image = "img/plates/$id.{$this->img_url->extension}";
                $this->img_url->saveAs($image);
                $image = "@web/$image";
            }


            return $image;
        } else {
            return false;
        }
    }

    public static function customFilter($array)
    {
        if (empty($array)) return false;

        foreach ($array as $i => $element)
        {
            if (empty($element['id']) || empty($element['amount']) || (!empty($element['cost']) && !is_numeric($element['cost'])) || strlen($element['description']) > 255){
                unset($array[$i]);
            }
        }

        return $array;
    }
}

controllers/PlatesController.php
<?php

namespace app\controllers;

use app\components\Notificacion;
use app\models\Establishments;
use app\models\Foods;
use app\models\FoodsForm;
use app\models\OrderPlates;
use app\models\Orders;
use Yii;
use yii\web\Controller;
use app\models\Plates;
use app\models\PlatesForm;
use yii\helpers\Html;
use yii\web\UploadedFile;


class PlatesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (in_array($action->id, ['data', 'get-additionals'])) {
            $this->enableCsrfValidation = false;
        }

        if (parent::beforeAction($action)){
            if (Yii::$app->user->isGuest){
                return $this->redirect(['usuario/login']);
            }
        }

        return parent::beforeAction($action);
    }

    public function actionList()
    {
        return $this->render('list');
    }

    public function actionData(){
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $data = Yii::$app->request->post();
        $pos = ['id', 'name', 'description', 'cost', 'created_at', 'id'];

        $searchName = $data['columns'][0]['search']['value'];
        $searchDir = $data['columns'][1]['search']['value'];
        $conditions = ($searchName) ? "name LIKE '%$searchName%' OR description LIKE '%$searchDir%'":'';

        $order = $pos[$data['order'][0]['column']];
        $orderDir = $data['order'][0]['dir'] == 'asc' ? SORT_ASC : SORT_DESC;

        $query = Plates::find()
                        ->where($conditions)
                        ->andWhere(['plates.deleted' => 0]);

        if (Yii::$app->user->identity->id !== 1)
        {
            $query = $query->andWhere(['establishment_id' => Yii::$app->user->identity->establishment_id]);
        }

        $result = $query->orderBy([$order => $orderDir])
                        ->limit($data['length'])
                        ->offset($data['start'])
                        ->all();

        $total = Plates::find()->count();

        $response = [
            "draw"=> $data['draw'],
            "recordsTotal" => $total,
            "recordsFiltered" => $total,
            "data" => []
        ];

        foreach ($result as $row)
        {
            $response['data'][] = [
                Html::img($row->img_url, ['class' => 'pull-left img-responsive image-small']),
                Yii::$app->formatter->format($row->created_at, 'datetime'),
                $row->name,
                $row->description,
                Yii::$app->formatter->format($row->cost, 'currency'),
                Html::a('<button class="btn btn-primary" data-toggle="tooltip" title="Modificar"><i class="fa fa-cog"></i></button>', ['/plates/modify', 'id' => $row->id]).
                Html::a('<button class="btn btn-danger" data-toggle="tooltip" title="Eliminar"><i class="fa fa-trash"></i></button>', ['/plates/delete', 'id' => $row->id])
            ];
        }

        return $response;
    }

    public function actionNew()
    {
        $platesForm = new PlatesForm();
        $foodsModel = [new Foods];

        if (Yii::$app->request->isPost)
        {
            $platesForm->load(Yii::$app->request->post());
            if (!$platesForm->validate())
            {
                throw new \Exception($platesForm->errors);
            }
            $foods = FoodsForm::customFilter(Yii::$app->request->post()['Foods']);

            $transaction = Yii::$app->db->beginTransaction();
            // Sube la foto del plato primero.
            $platesForm->img_url = UploadedFile::getInstance($platesForm, 'img_url');

            $db_models = new Plates();
            $db_models->name        = $platesForm->name;
            $db_models->description = $platesForm->description;
            $db_models->cost        = $platesForm->cost;
            $db_models->establishment_id = Yii::$app->user->identity->establishment_id;
            $db_models->insert();
            $plate_id = Yii::$app->db->getLastInsertID();

            // Insertacada uno de las comidas adicionales del plato y los relaciona con el id del plato ingresado.
            if (!empty($foods))
            {
                foreach ($foods as $food)
                {
                    $new_food = new Foods;
                    $new_food->plate_id = $plate_id;
                    $new_food->name = $food['name'];
                    $new_food->description = $food['description'];
                    $new_food->cost = $food['cost'];
                    $new_food->insert();
                }
            }

            $image = $platesForm->upload(null, $plate_id);
            if ($image)
            {
                $db_models->img_url = $image;
            }

            // If insert successfull redirect to list...
            try
            {
                $db_models->save();

                $transaction->commit();

                if (Yii::$app->request->isAjax)
                {
                    Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return ['success' => 1];
                }
                return $this->redirect(['/plates/list']);
            }
            catch (\Throwable $e)
            {
                $transaction->rollBack();
                throw new \Exception("Se encontro un error en el registro: ".$e->getMessage());
            }
        }

        return $this->render('new', ['model' => $platesForm, 'foodsModel' => (empty($foodsModel)) ? [new Foods] : $foodsModel]);
    }

    public function actionModify($id){
        $platesForm = new PlatesForm();
        $foodsModel = Foods::find()->where(['plate_id' => $id, 'foods.deleted' => false])->all();
        $db_models = Plates::find()->where(['id' => $id, 'deleted' => false])->one();

        if (Yii::$app->request->isPost)
        {
            $platesForm->load(Yii::$app->request->post());
            if (!$platesForm->validate())
            {
                throw new \Exception($platesForm->errors);
            }
            $foods = FoodsForm::customFilter(Yii::$app->request->post()['Foods']);

            $transaction = Yii::$app->db->beginTransaction();

            $db_models->name        = $platesForm->name;
            $db_models->description = $platesForm->description;
            $db_models->cost        = $platesForm->cost;
            $db_models->establishment_id = Yii::$app->user->identity->establishment_id;
            $db_models->updated_at  = date('Y-m-d H:i:s');

            // Insertacada uno de las comidas adicionales del plato y los relaciona con el id del plato ingresado.
            Foods::softDeleteAll(['plate_id' => $db_models->id]);
            foreach ($foods as $food)
            {
                $new_food = new Foods;
                $new_food->plate_id = $db_models->id;
                $new_food->name = $food['name'];
                $new_food->description = $food['description'];
                $new_food->cost = empty($food['cost']) ? 0 : $food['cost'];
                $new_food->insert();
            }

            $platesForm->img_url = UploadedFile::getInstance($platesForm, 'img_url');
            $image = $platesForm->upload($db_models->img_url, $db_models->id);

            if ($image)
            {
                $db_models->img_url = $image;
            }


            // If save successfull redirect to list...
            try
            {
                $db_models->save();
                $transaction->commit();
                return $this->redirect(['plates/list']);
            }
            catch (\Throwable $e)
            {
                $transaction->rollBack();
                throw new \Exception("Se encontro un error en la institucion: ".$e->getMessage());
            }
        }

        // Set value to inputs
        $platesForm->name        = $db_models->name;
        $platesForm->description = $db_models->description;
        $platesForm->img_url     = $db_models->img_url;
        $platesForm->cost        = $db_models->cost;

        return $this->render('modify', ['model' => $platesForm, 'foodsModel' => (empty($foodsModel)) ? [new Foods] : $foodsModel]);
    }

    public function actionDelete($id){
        $transaction = Yii::$app->db->beginTransaction();

        try
        {
            if (OrderPlates::find()->where(['plate_id' => $id])->count())
            {
                throw new \Exception("No se permite eliminar platos con ordenes existentes.");
            }

            Foods::softDeleteAll(['plate_id' => $id]);
            $model = Plates::find()->where(['Id' => $id])->one();

            if (empty($model)) {
                throw new \Exception("Plate not found");
            }

            $model->deleted = true;
            $model->save();

            $transaction->commit();
            return $this->redirect(['plates/list']);
        }
        catch (\Exception $e)
        {
            $transaction->rollBack();
            throw new \Exception($e);
        }
    }

    public function actionGetPlate($id){
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if (empty($id)){
            return ['data' => []];
        }
        $plate = Plates::find()->joinWith('foods')->where(['plates.id' => $id])->one();

        return ['data' => $plate, 'foods' => $plate->foods];
    }
}

views/plates/componentsElement.php
<div class="row">
    <div class="form-group">
        <?php use wbraganca\dynamicform\DynamicFormWidget;
        use yii\helpers\Html;

        DynamicFormWidget::begin([
            'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
            'widgetBody' => '.panel-body', // required: css class selector
            'widgetItem' => '.item', // required: css class
            'limit' => 4, // the maximum times, an element can be cloned (default 999)
            'min' => 1, // 0 or 1 (default 1)
            'insertButton' => '.add-item', // css class
            'deleteButton' => '.remove-item', // css class
            'model' => $foodsModel[0],
            'formId' => 'dynamic-form',
            'formFields' => [
                'name',
                'description',
                'cost',
            ],
        ]); ?>
        <div class="container-items"><!-- widgetContainer -->
            <div class="panel panel-default"><!-- widgetBody -->
                <div class="panel-heading">
                    <h3 class="panel-title pull-left">Complementos</h3>
                    <div class="pull-right">
                        <button type="button" title="Añadir nuevo" class="add-item btn btn-success btn-xs"><i class="glyphicon glyphicon-plus"></i></button>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="panel-body">
                    <?php foreach ($foodsModel as $i => $food){ ?>
                        <?php
                        // necessary for update action.
                        if (! $food->isNewRecord) {
                            echo Html::activeHiddenInput($food, "[{$i}]id");
                        }
                        ?>
                        <div class="item row">
                            <div class="col-sm-3">
                                <?= $form->field($food, "[{$i}]name")->textInput(['placeholder' => 'Nombre de la comida', 'maxlength' => true])->label('Nombre') ?>
                            </div>
                            <div class="col-sm-3">
                                <?= $form->field($food, "[{$i}]description")->textInput(['placeholder' => 'Descripcion', 'maxlength' => true])->label('Descripcion') ?>
                            </div>
                            <div class="col-sm-3">
                                <?= $form->field($food, "[{$i}]cost")->input('number', ['maxlength' => true, 'placeholder' => 'Valor agregado', 'step' => 'any'])->label('Costo adicional') ?>
                            </div>
                            <div class="col-md-3"><br>
                                <button type="button" title="Remover complemento" class="remove-item btn btn-danger btn-xs"><i class="glyphicon glyphicon-minus"></i></button>
                            </div>
                        </div><!-- .row -->
                    <?php } ?>
                </div>
            </div>
        </div>
        <?php DynamicFormWidget::end(); ?>
    </div>
</div>

views/plates/list.php
<?php
use  yii\helpers\Html;
use  yii\helpers\Url;
?>


<div class="x_content">
    <div class="row">
        <h1>Menu 1</h1>
    </div>
    <div class="row">
        <div class="col-md-4 input-group">
            <input type="text" placeholder="Buscador" id="buscador" class="form-control">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
            </span>
        </div>
        <div class="col-md-2">
            <?= Html::a('<button class="btn btn-primary"><i class="fa fa-plus"></i> Crear nueva</button>', ['plates/new']) ?>
        </div>
    </div>

    <hr>
    <div class="table-responsive">
        <table id="datatable" class="table table-striped table-bordered">
            <thead>
            <tr>
                <th width="7%">Foto</th>
                <th width="8%">Fecha Creacion</th>
                <th>Nombre</th>
                <th>Descripcion</th>
                <th>Costo</th>
                <th width="8%">accion</th>
            </tr>
            </thead>
        </table>
    </div>

</div>
<script>
    url = '<?=Url::to(['plates/data']);?>'
</script>
<?php
$this->registerJsFile(
    '@web/js/basic-table.js',
    ['depends' => [\yii\web\JqueryAsset::className(), 'fedemotta\datatables\DataTablesAsset',]]
);
?>

views/plates/modify.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>


<h2>Modificar plato <?=$model->name?></h2>
<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data', 'id' => 'dynamic-form']]) ?>

    <div class="row">
        <div class="form-group">
            <div class="col-md-4">
                <?= $form->field($model, 'name')->textInput()->input('text', ['placeholder' => 'Nombre'])->label('Nombre del plato') ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <div class="col-md-4">
                <?= $form->field($model, 'description')->textInput()->input('text', ['placeholder' => 'Descripcion'])->label('Corta descripcion del plato') ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <div class="col-md-4">
                <?= $form->field($model, 'cost')->textInput()->input('number', ['placeholder' => 'Valor', 'step' => 'any'])->label('Valor del plato') ?>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-group">
            <div class="col-md-4">
                <?= $form->field($model, 'img_url')->fileInput() ?>
                <label>Imagen actual</label>
                <br>
                <?=Html::img($model->img_url, ['class' => 'pull-left img-responsive image-preview']); ?>
            </div>
        </div>
    </div>
    <br>
<?= $this->render('componentsElement', ['form' => $form, 'foodsModel' => $foodsModel]) ?>

    <br>
    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class'=> 'btn btn-primary']); ?>
    </div>

<?php $form->end() ?>

views/plates/new.php
<?php

use wbraganca\dynamicform\DynamicFormWidget;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>

<h2>Crear nueva plato</h2>
<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data', 'id' => 'dynamic-form']]) ?>

<div class="row">
    <div class="form-group">
        <div class="col-md-4">
            <?= $form->field($model, 'name')->textInput()->input('text', ['placeholder' => 'Nombre'])->label('Nombre del plato') ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="form-group">
        <div class="col-md-4">
            <?= $form->field($model, 'description')->textInput()->input('text', ['placeholder' => 'Descripcion'])->label('Corta descripcion del plato') ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="form-group">
        <div class="col-md-4">
            <?= $form->field($model, 'cost')->textInput()->input('number', ['placeholder' => 'Valor', 'step' => 'any'])->label('Valor del plato') ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group">
        <div class="col-md-4">
            <?= $form->field($model, 'img_url')->fileInput() ?>
        </div>
    </div>
</div>


<?= $this->render('componentsElement', ['form' => $form, 'foodsModel' => $foodsModel]) ?>

<div class="form-group">
    <?= Html::submitButton('Guardar', ['class'=> 'btn btn-primary']); ?>
</div>


<?php ActiveForm::end() ?>