controllers/UsuarioController.php
<?php

namespace app\controllers;

use app\components\Notificacion;
use app\models\UsersModForm;
use app\models\UsersPasswordForm;
use Yii;
use yii\web\Controller;
use app\models\LoginForm;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\Users;
use app\models\UsuarioConfiguraciones;
use app\models\UsersForm;
use yii\helpers\Html;

class UsuarioController extends Controller
{

    public function beforeAction($action)
    {
        if ($action->id == 'login')
        {
            return parent::beforeAction($action);
        }

        if ($action->id == 'data') {
            $this->enableCsrfValidation = false;
        }

        if (parent::beforeAction($action)){
            if (Yii::$app->user->isGuest){
                return $this->redirect(['usuario/login']);
            }
        }

        return parent::beforeAction($action);
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['listado', 'configuracion', 'nuevo', 'modificar', 'borrar'],
                'rules' => [
                    [
                        'actions' => ['listado', 'configuracion', 'modificar', 'nuevo', 'borrar'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->Permiso === 'administrador';
                        },
                    ],
                    [
                        'actions' => ['modificar'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->id == Yii::$app->request->get()['id'];
                        },
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionListado()
    {
        return $this->render('listado');
    }

    public function actionData(){
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $data = Yii::$app->request->post();
        $pos = ['U.UpdatedAt', 'U.Usuario', 'U.Permiso', 'UC.EmailRespuesta', 'U.Estado', 'U.Id'];

        $searchName = $data['columns'][0]['search']['value'];
        $searchDir = $data['columns'][1]['search']['value'];
        $conditions = ($searchName) ? "(U.Usuario LIKE '%$searchName%' OR U.Permiso LIKE '%$searchDir%' OR UC.EmailRespuesta LIKE '%$searchDir%')":'';

        $order = $pos[$data['order'][0]['column']];
        $orderDir = $data['order'][0]['dir'] == 'asc' ? SORT_ASC : SORT_DESC;

        $query = Users::find()
            ->alias('U')
            ->select('U.*, UC.EmailRespuesta')
            ->leftJoin('UsuarioConfiguraciones UC', 'UC.IdUsuario = U.Id')
            ->where($conditions);

        if ($data['filterRole'])
        {
            $query = $query->andWhere(['U.Permiso' => $data['filterRole']]);
        }

        if ($data['filterStatus'] || $data['filterStatus'] === '0')
        {
            $query = $query->andWhere(['U.Estado' => $data['filterStatus']]);
        }


        $result = $query->andWhere('U.Id <> '.Yii::$app->user->identity->Id)
            ->orderBy([$order => $orderDir])
            ->limit($data['length'])
            ->offset($data['start'])
            ->createCommand()
            ->queryAll();
        $total = Users::find()->count();

        $response = [
            "draw"=> $data['draw'],
            "recordsTotal" => $total,
            "recordsFiltered" => $total,
            "data" => []
        ];

        foreach ($result as $row)
        {
            $response['data'][] = [
                Yii::$app->formatter->format($row['CreatedAt'], 'datetime'),
                $row['Usuario'],
                $row['Permiso'],
                !$row['EmailRespuesta'] ? '-' : $row['EmailRespuesta'],
                $row['Estado'] ? 'Activo' : 'Inabilitado',
                Html::a('<button class="btn btn-primary" data-toggle="tooltip" title="Modificar"><i class="fa fa-cog"></i></button>', ['/usuario/modificar', 'id' => $row['Id']]).
                Html::a('<button class="btn btn-danger" data-toggle="tooltip" title="Eliminar"><i class="fa fa-times"></i></button>', ['/usuario/borrar', 'id' => $row['Id']])
            ];
        }

        return $response;
    }

    public function actionNuevo()
    {
        $model = new UsersForm();

        if ($model->load(Yii::$app->request->post()))
        {
            $transaction = Yii::$app->db->beginTransaction();
            try
            {
                // Primero prueba que los datos de email funcionen:
                if (!$this->testEmailServer($model))
                {
                    throw new \Exception("Los datos de email no son validos: ");
                }

                $nuevoUsuario = new Users();
                $nuevoUsuario->Usuario     = $model->usuario;
                $nuevoUsuario->Permiso     = $model->permiso;
                $nuevoUsuario->Password    = sha1($model->password);
                /** @noinspection PhpUndefinedFieldInspection */
                $nuevoUsuario->IdUsuarioCreador = Yii::$app->user->identity->Id;
                $nuevoUsuario->CreatedAt   = date('Y-m-d H:i:s');
                $nuevoUsuario->insert();
                $user_id = Yii::$app->db->getLastInsertID();

                $nuevoUsuarioConfig = new UsuarioConfiguraciones();
                $nuevoUsuarioConfig->IdUsuario = $user_id ;
                $nuevoUsuarioConfig->EmailRespuesta = $model->email_respuesta;
                $nuevoUsuarioConfig->insert();

                $transaction->commit();

                Notificacion::Notificar(
                    'Usuario nuevo',
                    'Un nuevo usuario dado de alta: '.$nuevoUsuario->Usuario,
                    ['precotizacion/modificar', 'id' => $user_id]
                );

                return $this->redirect(['/usuario/listado']);
            }
            catch (\Throwable $e)
            {
                $transaction->rollBack();
                throw new \Exception("Se encontro un error en el registro: ".$e->getMessage());
            }
        }

        return $this->render('nuevo', ['model' => $model]);
    }

    public function actionBorrar($id){
        $model = Users::find()->where(['Id' => $id])->one();

        if (empty($model)){
            throw new \Exception("Usuario requerido no encontrada");
        }

        $model->delete();

        return $this->redirect(['usuario/listado']);
    }

    public function actionModify($id){
        $model = new UsersModForm();
        $usuario = Users::find()->where(['Id' => $id])->one();
        $usuarioConfig = UsuarioConfiguraciones::find()->where(['IdUsuario' => $usuario->Id])->one();

        if ($model->load(Yii::$app->request->post()))
        {
            $transaction = Yii::$app->db->beginTransaction();
            try
            {
                // Primero prueba que los datos de email funcionen:
                if (!$this->testEmailServer($model))
                {
                    throw new \Exception("Los datos de email no son validos: ");
                }

                $usuario->Usuario     = $model->usuario;
                $usuario->Permiso     = $model->permiso;
                /** @noinspection PhpUndefinedFieldInspection */
                $usuario->IdUsuarioCreador = Yii::$app->user->identity->Id;
                $usuario->UpdatedAt = date('Y-m-d H:i:s');
                $usuario->save();

                $usuarioConfig->EmailRespuesta = $model->email_respuesta;
                $usuarioConfig->save();

                $transaction->commit();

                return $this->redirect(['/usuario/listado']);
            }
            catch (\Throwable $e)
            {
                $transaction->rollBack();
                throw new \Exception("Se encontro un error en el registro: ".$e->getMessage());
            }
        }

        // Set value to inputs}

        $model->usuario = $usuario->Usuario;
        $model->permiso = $usuario->Permiso;
        $model->email_respuesta = $usuarioConfig->EmailRespuesta;
        $model->email_prueba = $usuarioConfig->EmailPrueba;

        $model2 = new UsersPasswordForm();

        return $this->render('modificar', ['model' => $model, 'model2' => $model2, 'id' => $id]);
    }

    public function actionModificarPerfil($id){
        $model = new UsersModForm();
        $usuario = Users::find()->where(['Id' => $id])->one();
        $usuarioConfig = UsuarioConfiguraciones::find()->where(['IdUsuario' => $usuario->Id])->one();

        if ($model->load(Yii::$app->request->post()))
        {
            $transaction = Yii::$app->db->beginTransaction();
            try
            {
                // Primero prueba que los datos de email funcionen:
                if (!$this->testEmailServer($model))
                {
                    throw new \Exception("Los datos de email no son validos: ");
                }

                $usuario->Usuario     = $model->usuario;
                /** @noinspection PhpUndefinedFieldInspection */
                $usuario->IdUsuarioCreador = Yii::$app->user->identity->Id;
                $usuario->UpdatedAt = date('Y-m-d H:i:s');
                $usuario->save();

                $usuarioConfig->EmailRespuesta = $model->email_respuesta;
                $usuarioConfig->save();

                $transaction->commit();

                return $this->redirect(['/usuario/listado']);

views/usuario/listado.php
<?php
use  yii\helpers\Html;
use  yii\helpers\Url;
use brussens\bootstrap\select\Widget as Select;

?>


<div class="x_content">
    <div class="row">
        <h1>Listado de usuarios</h1>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="input-group">
                <?= Html::input('text', '', '', ['class' => 'form-control', 'id' => 'buscador', 'placeholder' => 'Buscador']) ?>
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">Buscar</button>
                </span>
            </div>
        </div>
        <div class="col-md-2">
            <?= Html::a('<button class="btn btn-primary"><i class="fa fa-plus"></i> Nuevo usuario</button>', ['usuario/nuevo']) ?>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-2">
            <?= Html::label('Rol de usuario', 'RoleFilter') ?>
            <?= Select::widget([
                'name' => 'roleFilter',
                'items' => ['administrador' => 'Administrador', 'sincronizador' => 'Sincronizador', 'autorizador' => 'Autorizador', 'basico' => 'Basico'],
                'options' => [
                    'id' => 'RoleFilter',
                    'class' => 'form-control',
                    'data-live-search' => 'true',
                    'prompt'=>'Todos'
                ]
            ]) ?>
        </div>
        <div class="col-md-2">
            <?= Html::label('Estado', 'StatusFilter') ?>
            <?= Select::widget([
                'name' => 'statusFilter',
                'items' => ['1' => 'Activo', '0' => 'Inabilitado'],
                'options' => [
                    'id' => 'StatusFilter',
                    'class' => 'form-control',
                    'data-live-search' => 'true',
                    'prompt'=>'Todos'
                ]
            ]) ?>
        </div>
    </div>

    <hr>
    <div class="table-responsive">
        <table id="datatable" class="table table-striped table-bordered">
            <thead>
            <tr>
                <th width="12%">Ultima actualizacion</th>
                <th>Usuario</th>
                <th>Rol</th>
                <th>Email</th>
                <th>Estado</th>
                <th width="8%">Accion</th>
            </tr>
            </thead>
        </table>
    </div>

</div>
<script>
    url = '<?=Url::to(['usuario/data']);?>'
</script>
<?php
$this->registerJsFile(
    '@web/js/usuario.js',
    ['depends' => [\yii\web\JqueryAsset::className(), 'fedemotta\datatables\DataTablesAsset',]]
);
?>

views/usuario/login.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;

?>

<?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="center-content">
            <div class="panel panel-default">
                <h1>Acceso de personal</h1>
                <?=Html::img('@web/img/PROGRAM-Logo.png', ['class' => 'img-responsive'])?>
                <div class="panel-body">
                <div class="form-group">
                    <?= $form->field($model, 'name')->textInput(['autofocus' => true])->label('Usuario') ?>
                </div>
                <div class="form-group">
                    <?= $form->field($model, 'password')->passwordInput()->label('Contraseña') ?>
                </div>
                <div class="form-group">
                    <?= $form->field($model, 'rememberMe')->checkbox([
                        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
                    ], [])->label('No cerrar sesion ') ?>
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Iniciar sesion', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

views/usuario/modificar-perfil.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use brussens\bootstrap\select\Widget as Select;
?>

    <h2>Modificar Perfil</h2>
<?php $form = ActiveForm::begin(['options' => ['autocomplete' => 'off']]) ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'usuario')->textInput()->input('text', ['placeholder' => 'Nombre de usuario'])->label('Nombre de usuario') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'email_respuesta')->textInput()->input('email', ['placeholder' => 'Email para notificaciones'])->label('Email para notificaciones') ?>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-4">
            <?= Html::submitButton('Guardar', ['class'=> 'btn btn-primary']); ?>
        </div>
    </div>

<?php ActiveForm::end() ?>
<br><br><br>
<?php $form = ActiveForm::begin(['action' => ['usuario/modificar-password', 'id' => $id], 'options' => ['autocomplete' => 'off']]); ?>
<h2>Cambiar contraseña</h2>
<div class="row">
    <div class="col-md-4">
        <?= $form->field($model2, 'new_password')->textInput()->input('password', ['placeholder' => 'Ingrese su nueva contraseña', 'autocomplete'=>"new-password"])->label('Ingrese su nueva contraseña') ?>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <?= $form->field($model2, 'password_repeat')->textInput()->input('password', ['placeholder' => 'Repita su contraseña', 'autocomplete'=>"new-password"])->label('Repita su contraseña') ?>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-4">
        <?= Html::submitButton('Guardar', ['class'=> 'btn btn-primary']); ?>
    </div>
</div>
<?php $form->end(); ?>

views/usuario/modificar.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use brussens\bootstrap\select\Widget as Select;
?>

    <h2>Modificar usuario</h2>
<?php $form = ActiveForm::begin(['options' => ['autocomplete' => 'off']]) ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'usuario')->textInput()->input('text', ['placeholder' => 'Nombre de usuario'])->label('Nombre de usuario') ?>
        </div>
    </div>
<?php
    if (Yii::$app->user->identity->Permiso == 'administrador') {
?>
    <div class="row">
        <div class="col-md-4">
            <?=$form->field($model, 'permiso')->widget(Select::className(), [
                'options' => ['data-live-search' => 'true', 'prompt'=>'Seleccione'],
                'items' => ['administrador' => 'Administrador', 'sincronizador' => 'Sincronizador', 'autorizador' => 'Autorizador', 'basico' => 'Basico']
            ])->label('Rol de usuario');?>
        </div>
    </div>
<?php
}
?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'email_respuesta')->textInput()->input('email', ['placeholder' => 'Email para notificaciones'])->label('Email para notificaciones') ?>
        </div>
    </div>
    <hr>
    <div class="row">
        <?= Html::submitButton('Guardar', ['class'=> 'btn btn-primary']); ?>
    </div>

<?php ActiveForm::end() ?>

<?php $form = ActiveForm::begin(['action' => ['usuario/modificar-password', $id], 'options' => ['autocomplete' => 'off']]); ?>
<h2>Cambiar contraseña</h2>
<!--<div class="row">
    <div class="col-md-4">
        <?/*= $form->field($model2, 'old_password')->textInput()->input('password', ['placeholder' => 'Ingrese su actual contraseña'])->label('Ingrese su actual contraseña') */?>
    </div>
</div>-->
<div class="row">
    <div class="col-md-4">
        <?= $form->field($model2, 'new_password')->textInput()->input('password', ['placeholder' => 'Ingrese su nueva contraseña', 'autocomplete'=>"new-password"])->label('Ingrese su nueva contraseña') ?>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <?= $form->field($model2, 'password_repeat')->textInput()->input('password', ['placeholder' => 'Repita su contraseña', 'autocomplete'=>"new-password"])->label('Repita su contraseña') ?>
    </div>
</div>
<?php $form->end(); ?>

views/usuario/nuevo.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use brussens\bootstrap\select\Widget as Select;
?>

<h2>Crear nuevo usuario</h2>
<?php $form = ActiveForm::begin(['options' => ['autocomplete' => 'off']]) ?>
<div class="row">
    <div class="col-md-4">
        <?= $form->field($model, 'usuario')->textInput()->input('text', ['placeholder' => 'Nombre de usuario'])->label('Nombre de usuario') ?>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <?=$form->field($model, 'permiso')->widget(Select::className(), [
            'options' => ['data-live-search' => 'true', 'prompt'=>'Seleccione'],
            'items' => ['administrador' => 'Administrador', 'sincronizador' => 'Sincronizador', 'autorizador' => 'Autorizador', 'basico' => 'Basico']
        ])->label('Rol de usuario');?>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <?= $form->field($model, 'password')->textInput()->input('password', ['placeholder' => 'Ingrese su contraseña', 'autocomplete'=>"new-password"])->label('Contraseña') ?>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <?= $form->field($model, 'password_repeat')->textInput()->input('password', ['placeholder' => 'Repita su contraseña', 'autocomplete'=>"new-password"])->label('Repita su contraseña') ?>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <?= $form->field($model, 'email_respuesta')->textInput()->input('email', ['placeholder' => 'Email para notificaciones'])->label('Email para notificaciones') ?>
    </div>
</div>
<hr>
<div class="row">
    <?= Html::submitButton('Guardar', ['class'=> 'btn btn-primary']); ?>
</div>

<?php ActiveForm::end() ?>